### ISSUE TITLE
Request: Automatic HTML Sanitizing in Standard Components

### ISSUE THREAD

**Issue by ScraM-Team** [konsoletyper/teavm-flavour#11]
It would help people secure their applications if the standard components (<html:text>, etc.) sanitized displayed text using the OWASP Sanitizing library ( https://www.owasp.org/index.php/OWASP_Java_HTML_Sanitizer_Project ) or something similar.

Other projects have started doing this (see https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks ) to block XSS attacks.

If performance or bloat is a concern, perhaps this could be made optional.  Some projects would be willing to make this tradeoff in the name of security.

**Comment by konsoletyper** [comment]
Sorry, I don't see any purpose on doing that. Flavour templating *is not* text based. It parses HTML and builds JavaScript that recreates DOM. This will automatically block different kinds of attacks. Or is there something that I miss?

**Comment by ScraM-Team** [comment]
If the user entered malicious JavaScript for their name, then the Flavour code:

`<html:text value="name">`

will place the malicious JavaScript on the page.  (If name is a variable loaded from user-entered data stored in a database or elsewhere.)

If we change TextComponent line 57 ( https://github.com/konsoletyper/teavm-flavour/blob/master/templates/src/main/java/org/teavm/flavour/components/html/TextComponent.java ) to use a sanitizing library:

`[...] .createTextNode(sanitizer.sanitize(String.valueOf(computedValue))))`

Then any JavaScript in the 'name' string will be escaped and won't execute.

Most developers will reject script syntax at entry time.  However, in case somebody forgets, sanitizing the output is a good second layer of defense against XSS attacks.

**Comment by konsoletyper** [comment]
How can 'createTextNode' inject any script on a web page?

**Comment by ScraM-Team** [comment]
[mind blown]  Thanks for clarifying!  So an attempt to inject a script just results in the script being printed?  Very cool.  That is a huge advantage for Flavour -- strong XSS protection.

**Comment by ScraM-Team** [comment]
After spending some time on this with my team, we can't find any way to accomplish XSS via the standard Flavour components.  The only way we were able to cause JavaScript to be executed was by invoking setInnerHtml(), which is known to be dangerous and would show up on any security review.

My one suggestion is that setInnerHtml() be renamed dangerouslySetInnerHtml(), like at least one other framework has done, so any caller knows they are taking a risk by bypassing the built-in, secure APIs.

And again, great work @konsoletyper !  Any comparison of TeaVM should emphasize the built-in security from now on.

**Comment by konsoletyper** [comment]
`setInnerHtml` is nothing more than binding to DOM API provided by browsers. You can examine this method and see that there's no implementation at all. So if you are concerned about security issues with this method, you better address your thoughts to W3C, Chromium contributors, etc. As for Flavour, it was not meant that user would often call DOM directly, so I don't see if any security issue exists here.
