### ISSUE TITLE
Creating new array failes

### ISSUE THREAD

**Issue by rufenerc** [konsoletyper/teavm-flavour#2]
The following code fails at runtime with a:
"Uncaught TypeError: Cannot read property 'data' of undefined" error

/****/
int t[][] = new int[0][0];
System.out.println("t length = " + t.length);

**Comment by konsoletyper** [comment]
How it's related to `teavm-flavour`. Maybe, you meant [TeaVM](https://github.com/konsoletyper/teavm)? Anyway, you provided too few information to reproduce the problem. What version of TeaVM are you using? Can you give self-contained project that helps to reproduce the issue?

**Comment by rufenerc** [comment]
Sorry, I was on the wrong project. It's indeed TeaVM. 
I will describe it there.
Sorry again.
