### ISSUE TITLE
Mixing Flavour with DOM Manipulation Confuses Flavour

### ISSUE THREAD

**Issue by ScraM-Team** [konsoletyper/teavm-flavour#20]
I have a View class which performs some direct DOM manipulation of elements (create, add) inside a std:if component.  This eventually causes errors about trying to add a component that already has a parent.

My guess is that Flavour and direct DOM manipulation are fundamentally incompatible.
* If so, this should be explicitly stated so people know to avoid this issue.
* If they are meant to work together, then I will create a small example that shows the problem.

**Comment by konsoletyper** [comment]
No, you can't modify DOM directly from within view. You should define custom components and wrap your DOM into virtual DOM (Slot class). There's no documentation on direct DOM manipulation, but you can look through Flavour's standard components source code to learn how to do this. To learn how to create custom components, see http://teavm.org/docs/flavour/custom-components.html

**Comment by ScraM-Team** [comment]
Cool, thanks for letting me know.  It makes sense -- once Flavour has its own wrappers around the DOM, external changes won't be tracked.

I will change my code to use standard Flavour components or create my own.

You can close this if you'd like, it sounds like user error now that you've explained it.

**Comment by ScraM-Team** [comment]
I have updated the Flavour documentation in a PR:

https://github.com/konsoletyper/teavm-site/pull/23
