### ISSUE TITLE
Order Not Saving

### ISSUE THREAD

**Issue by aa2858** [konsoletyper/teavm-flavour#58]
Hi, 

I am getting this exception when saving an order.  Product is saving to the database only orderitem.

java.lang.IllegalArgumentException: Can't serialize object of type org.teavm.flavour.example.model.OrderStatus
(anonymous) @ classes.js:448

Thanks,
Adams

**Comment by ScraM-Team** [comment]
OrderStatus probably needs the @JsonPersistable annotation.

**Comment by ScraM-Team** [comment]
The @JsonPersistable annotation is now required on all entities and enums parsed by Flavour.

This is documented here: http://teavm.org/docs/flavour/json.html

"Unlike normal Jackson, Flavour requires that all persistable classes are marked with @org.teavm.flavour.json.JsonPersistable annotation."

Right before "public class", add @JsonPersistable, and have your IDE add the right import.  Do this for
* OrderStatus
* Order
* OrderItem
* Product

and it should work.

If you get it working, please create a PR with the changes.  It will help future Flavour developers.  Thank you!

**Comment by aa2858** [comment]
@ScraM-Team 
Your suggestion fixes the issue and I have created the PR as suggested.

Thanks!
