### ISSUE TITLE
Where is Documentation for Flavour?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [konsoletyper/teavm-flavour#77]
Did something happen to the doco for Flavour?

The link for this repo points to the TeaVM doc site but I no longer see any documentation there for Flavour

**Comment by konsoletyper** [comment]
This project is no more maintained, that's why I removed documentation from TeaVM site

**Comment by xvik** [comment]
Old flavour docs could be found [here](https://frequal.com/teavm-site/docs/flavour/templates.html). This is a flavour [fork](https://flavour.sourceforge.io/) (not very active - compatible only with teavm 0.8, at least when I was checking last time) ([source](https://sourceforge.net/projects/flavour/))
